inline_rules:
  - id: avoid-print-statements
    pattern: "print("
    message: "Avoid using `print()` for logging. Use a standard logging framework like `logging` instead."
    severity: warning

  - id: mutable-default-args
    pattern: "=[]"
    message: "Avoid mutable default arguments like lists or dicts. Use None and set defaults inside the function."
    severity: error

  - id: hardcoded-credentials
    pattern: "(?i)(password|secret|token).*="
    message: "Avoid hardcoding sensitive credentials. Use environment variables or config management tools."
    severity: error

  - id: use-constants
    pattern: "= [0-9]+"
    message: "Magic numbers detected. Use named constants for better readability and maintainability."
    severity: info

  - id: avoid-bare-except
    pattern: "except:"
    message: "Avoid bare `except:`. Be explicit about the exception you want to catch."
    severity: warning

  - id: inline-todo-comments
    pattern: "#.*TODO"
    message: "TODO comment detected. Make sure unresolved tasks are tracked in your issue tracker."
    severity: info

  - id: line-too-long
    regex: true
    pattern: "^.{101,}$"
    message: "Line exceeds 100 characters. Consider breaking it into multiple lines."
    severity: info

  - id: bad-variable-naming
    regex: true
    pattern: "\\b[a-zA-Z]{1,2}\\b"
    message: "Avoid single-character variable names unless in a loop or mathematical context."
    severity: info

  - id: import-star
    pattern: "from .* import \\*"
    message: "Avoid wildcard imports. Import only what you need to prevent namespace pollution."
    severity: warning

  - id: direct-os-system-calls
    pattern: "os.system("
    message: "Avoid using `os.system()`. Prefer `subprocess.run()` with proper sanitization."
    severity: warning
